sudo: required
services: 
  - docker
env: 
  global: 
    - GIT_SHA=$(git rev-parse HEAD) 
    - CLOUDSDK_CORE_DISABLE_PROMPT=1
before_install: 
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc 
  - gcloud components update kebectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project future-surge-264220
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 
  - docker build -t billweng/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true billweng/react-test npm run test 

deploy: 
  provider: script 
  script: bash ./deploy.sh
  on: 
    branch: master


